db:
  # sample::
  #   host: "localhost"
  #   port: "3306"
  #   dbName: "go_scraper"
  #   user: "user"
  #   password: "password"
  dbName: "go_scraper"
  user: "user"
  password: "password"
baseURL: "http://localhost:3000/"
notFoundMessage: "ページが存在しません"
